# Etapa 1: build da aplicação Angular com SSR
FROM node:20-alpine as builder

WORKDIR /app

# Copia os arquivos de dependência
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia todo o projeto
COPY . .

# Build SSR (client + server)
RUN npm run build

# Etapa 2: imagem de produção
FROM node:20-alpine

WORKDIR /app

# Copia somente o necessário para rodar a app
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/package.json /app/package.json

# Porta que o Express usa
EXPOSE 4000

# Comando para iniciar o servidor SSR
CMD ["node", "dist/sintetiza-frontend/server/server.mjs"]
